# Generated by Django 3.2.15 on 2022-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
